### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by CChalu** [openSUSE/openSUSE-docs-revamped-temp#1]
Hi, 
Great idea this documentation!
Will it be available only in English or can we translate it?
It seems to be impossible to translate official documentation (Startup Guide, Reference Guide, ...) with weblate or github.
The principle of the release notes is good: if there is a version in the user's language, it is displayed, otherwise the English version is displayed. The translation with weblate is very useful.
Thank you for this initiative of documentation for beginners (and others)

On demo site, github link is broken.

**Comment by why-not-try-calmer** [comment]
Hi, thanks for your question and for pointing out the deprecated references (just fixed them)!
We really want to translate the docs, but before that, it needs to be a bit more mature, by which I mean that it needs to undergo more reviews and have sections 1-9 complete. After that I'll be very much interested to help coordinate with translators (and yes, using weblate).

**Comment by CChalu** [comment]
> Hi, thanks for your question and for pointing out the deprecated references (just fixed them)!

There is now a bad URL in the README file with a double "temp"



> After that I'll be very much interested to help coordinate with translators (and yes, using weblate).

Great! Thanks

**Comment by why-not-try-calmer** [comment]
Fixed. I see you were involved in an another documentation project centered on the openSUSE distributions. So if you have comments, suggestions, or simply want to contribute ahead of a future translation to French, your experience will be highly appreciated! Have a great day

**Comment by CChalu** [comment]
I participate in translations of official openSUSE projects for beginners and intermediate users (like me) and I also initiated and participated in the translation of the unofficial guide to Leap 15.x. 
I will follow your project with interest!
Who should close the issue? you or me?
Have a nice day

**Comment by why-not-try-calmer** [comment]
To reopen after reaching beta.
