### ISSUE TITLE
List of ideas for short video contents

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped-temp#12]
In the recent months I have seen new users struggle a bit with simple tasks which are not easy to decompose into lists or not easy to work with from lists, mostly because they involve GUI interfaces or critical operations, where the back-and-forth between the screen and the list might be a little bit risky (what if the user skipped an important item?). 

The goal of this Issue is to enumerate them and see if someone would be interested to cover them, in the form of very short (1-3 min) video clips. I think focussing on this length would hugely increase the attractiveness.

1. picking the right image and preparing the media for a Live install
2. adding/removing repos
3. adding/removing packages from official repos
4. resizing a partition, system or swap
5. rolling back, switching snapshot
6. configuring network
7. configuring devices and peripherals

@apinter You want to do or oversee this? I have too much on my plate to ever start doing this.

_Tools probably needed_
- KDE Plasma (because that's what most people are using), ideally Wayland
- _bash_ (because any other shell will not be the shell of most people as they start using the distros)
- a tool for zooming in on cursor position and highligting portions of the image recorded
- a tool for overlaying texts
- OBS Studio
- a mic

**Comment by Ethanol6** [comment]
Would these videos need narration or text captions? What about translations?

**Comment by apinter** [comment]
I was toying with idea of these short to the point videos and tbh it is incredibly easy to do one if we keep it simple, no bells and whistles. For reference I did a bit on [YaST here](https://www.youtube.com/watch?v=p2K4uqxPJ8Q) and if this is what we're looking for I'm happy to do so.

@Ethanol6 check the video I linked and do let me know what do you think. Again, my intention was to keep it short and to the point and I think we could keep it that way in the future as well on topics @why-not-try-calmer mentioned. In regards to translations: we could make these videos accessible in a raw format that others could take and create their own narration or just create a subtitle with the translation. I'm not sure tbh so open for ideas ;)

**Comment by why-not-try-calmer** [comment]
> Would these videos need narration or text captions? What about translations?

I think we can postpone thinking about translation, because:

1. This would be a "pilot", to test how the community would be interested.
2. The more people liking the idea, the faster the translation.
3. The vids don't need to speak many words. Zoom ins on cursor movements, text overlays and done.

**Comment by Ethanol6** [comment]
My initial thought was to make up an FFMPEG script that does the work for us, including adding all the subtitles/translations automatically. This is probably overkill for a "pilot".

**Comment by why-not-try-calmer** [comment]
> Can we add the firewall settings to the list? eg. open ports for kdeconnect, wi-fi printer (mdns), send content to chromecast.
> Or maybe a video to configure eg. kdeconnect and within that video configure the firewall.

very good idea, updated

**Comment by Ethanol6** [comment]
I was thinking of using a slide from the oS artwork repo as the "intro" and table of contents. https://github.com/openSUSE/artwork/blob/master/slides/openSUSE-Template.otp

Maybe something different with Tumbleweed branding? Just throwing ideas out there.

**Comment by apinter** [comment]
> I was thinking of using a slide from the oS artwork repo as the "intro" and table of contents. https://github.com/openSUSE/artwork/blob/master/slides/openSUSE-Template.otp
> 
> Maybe something different with Tumbleweed branding? Just throwing ideas out there.

Agreed, but doubt that we would need a different one for Leap. I would unify as much as possible to avoid the maintenance-hell ^_^
Maybe we can modify it by adding a Leap and a TW logo?
