### ISSUE TITLE
image_choice.md Fedora Media Writer download links.

### ISSUE THREAD

**Issue by Ethanol6** [openSUSE/openSUSE-docs-revamped-temp#14]
Suggest to make the download links for FMW direct the user to here: [https://getfedora.org/en/workstation/download/](https://getfedora.org/en/workstation/download/) where the user can verify the source of the software.

Currently the links directly prompt to download the software. Some (most?) users may be wary about downloading unfamiliar software on their PC without first seeing where it is coming from.

Thoughts?

**Comment by why-not-try-calmer** [comment]
Sure, just lodge a PR!
