### ISSUE TITLE
microOS peer-reviewing

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped-temp#16]
Richard Brown has made some criticisms of the microOS documentation. I think it would be in the best interest of the community if Richard Brown could provide peer-reviewing expertise with regard to this portion of the documentation.

**Comment by why-not-try-calmer** [comment]
That's the other button, Ric.

**Comment by sysrich** [comment]
I will not be compelled/bullied into contributing to this repo.

**Comment by why-not-try-calmer** [comment]
😿
