### ISSUE TITLE
mkdocs versioning --> mike

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped-temp#30]
archived and no longer maintained: https://github.com/zayd62/mkdocs-versioning
good replacement: https://github.com/jimporter/mike

**Comment by Idesmi** [comment]
Since you have dismissed versioning in https://github.com/openSUSE/openSUSE-docs-revamped-temp/commit/700c8ad69af51787f8d228501c76d1949caba622, there's no need to add the mike plugin anymore?

**Comment by why-not-try-calmer** [comment]
There is indeed no need for it _right now_. But it might be prudent to keep the reference around in case things change. Relabelling though.
