### ISSUE TITLE
Does our documentation pertaining to NVIDIA achieve the goal mentioned below?

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped-temp#31]
https://www.reddit.com/r/openSUSE/comments/p4l25d/hybrid_graphics_laptops_with_opensuse_for_a/

**Comment by apinter** [comment]
Not sure as I don't spend money on hardware that is not supported well on Linux therefore I can't even confirm it. Maybe @thunderbirdtr has more the required expertise on the matter. 

OTOH - in regards to the Reddit post - I believe that without the Nvidia driver installed even if the GPU is turned off it will [still consume more power](https://www.youtube.com/watch?v=1kVQAjnwG0w)
