### ISSUE TITLE
Please mention printing in such a comprehensive overview, especially firewalld gotcha

### ISSUE THREAD

**Issue by gwhitney** [openSUSE/openSUSE-docs-revamped-temp#41]
I first installed OpenSUSE Tumbleweed several years ago, and used it successfully since then, but recently had to get a new computer and install from scratch again. All went reasonably well until I first wanted to print, and then nothing at all seemed to work and wasted an entire day until finally some search I managed to try turned up an obscure Reddit post about the default firewalld settings in recent times being so strict that they prevent using a networked printer.

I am not here to complain about those defaults, or even that the user is not warned about them anywhere in the installation process or in the YAST printer configuration process as far as I can tell. I am opening this issue to humbly suggest that in what's shaping up as a wonderful, comprehensive newbie-to-moderately-experienced guide about installing, configuring, and tuning OpenSUSE tumbleweed, there should be some mention about detecting and setting up printers (and maybe scanners and/or other peripheral devices), especially given that there is the potentially major pitfall out there that the firewall may be blocking YAST from detecting printers and CUPS from printing to them, even if one manages to manually configure them correctly.

I am happy to "put my writing where my mouth is" if someone can point me to the place within the docs structure that the organizers of this would like a few basic paragraphs on this topic as a starter; I'd be glad to do an initial PR to help resolve this issue. But I doubt I can be the ultimate authority here; I just got things working by turning off firewalld altogether, then configuring the printer and doing a test print, and then turning firewalld back on again, and then clicking various protocols that seemed relevant in the firewall-config tool until I could print again. But I may well have opened ports I didn't need to, for example, I really don't know.

Thanks for any pointers on how to address this documentation aspect -- I'd love to spare the next ~~victim~~ person installing Tumbleweed this pain. ;-)

**Comment by why-not-try-calmer** [comment]
I read so many complaints about firewalld settings that I cannot take this lightly. Yes, please help us get this straight. All you have to do is fork, clone and create an .md file under /project. We will walk you through all the steps afterwards, or these ones if you need. Welcome onboard!

**Comment by gwhitney** [comment]
I am quite familiar with the PR process; I was just concerned about whether I needed to worry about where and how my document fits into the outline/narrative flow of this guide. Any suggestions on that, or should I just write something standalone and a maintainer will fold it in one way or another? Thanks.

**Comment by why-not-try-calmer** [comment]
> I am quite familiar with the PR process; I was just concerned about whether I needed to worry about where and how my document fits into the outline/narrative flow of this guide. Any suggestions on that, or should I just write something standalone and a maintainer will fold it in one way or another? Thanks.

You can write something standalone and you should. You can mimick the style of other contents, such as the installer, zypper etc. And of course items (1-3) mentioned in my previous message :)

**Comment by Ethanol6** [comment]
Does #42 mean we can close this or are there additions to be made? If there are still lose ends, perhaps we should refine this issue to help guide other contributors.

**Comment by why-not-try-calmer** [comment]
Yes, I think so, you can close it
