### ISSUE TITLE
Add setup/build documentation for mkdocs

### ISSUE THREAD

**Issue by sknorr** [openSUSE/openSUSE-docs-revamped-temp#43]
It would be great if readme.md could provide an overview of how to get mkdocs set up (so I can visually check the output before making a PR).

**Comment by why-not-try-calmer** [comment]
Isn't what you are looking referenced under the second bullet point here https://github.com/openSUSE/openSUSE-docs-revamped-temp#contributing?

**Comment by sknorr** [comment]
It is. Sorry. Closing.
