### ISSUE TITLE
The GitHub Action fails to deploy to the gh-page branch

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/openSUSE-docs-revamped-temp#75]
Since a couple of weeks, maybe a month, the GitHub action has failed to _force push_ builds to the `gh-page` branch. I am still investigating the issue. In the meantime, using `mkdocs gh-deploy` does the same and works. (Even though the `gh-page` branch is protected, it should be writable by the action given the set permissions. Also we do need to force push and not just push since we want to produce a clean build on each push).

**Comment by sknorr** [comment]
Oh! Uhm. I did something on Friday -- namely made the `gh-pages` branch a protected branch which disables force-pushes. Sorry, I should have asked.

**Comment by sknorr** [comment]
I just allowed force-pushes again for `gh-pages`.
