### ISSUE TITLE
Upgrade from OpenSuse 12.1 To OpenSuse 15.4 - Steps or Document needed

### ISSUE THREAD

**Issue by Zayan1221** [openSUSE/openSUSE-docs-revamped-temp#93]
Hello ,
I need to Update from OpenSuse 12.1 to OpenSuse 15.4 - Can I have any steps ? or Documentation.

cat /etc/os-release
NAME=openSUSE
VERSION = 12.1 (Asparagus)
VERSION_ID="12.1"
PRETTY_NAME="openSUSE 12.1 (Asparagus) (x86_64)"
ID=opensuse

**Comment by why-not-try-calmer** [comment]
Hi, openSUSE has many places for user support:
- https://lists.opensuse.org/archives/list/users@lists.opensuse.org/
- https://forums.opensuse.org/forumdisplay.php/842-English
- https://reddit.com/r/openSUSE
- https://en.opensuse.org/openSUSE:IRC_list
and more to be found at https://get.opensuse.org/leap/.

Thanks for your understanding!
