### ISSUE TITLE
'microos_getting_started' page is not displaying any sensible content

### ISSUE THREAD

**Issue by tbazant** [openSUSE/openSUSE-docs-revamped-temp#94]
The page:

https://opensuse.github.io/openSUSE-docs-revamped-temp/safety_usability/microos_getting_started.md

is not displaying any sensible content, only wonky graphics and headers/footers.

**Comment by why-not-try-calmer** [comment]
Should be fixed with https://github.com/openSUSE/openSUSE-docs-revamped-temp/commit/be40286b759eb99244578d9a30f123fd193334a5.
